##spring:
##  datasource:
##    driver-class-name: org.h2.Driver
##    url: jdbc:h2:mem:localhost;
##    username: admin
##    password:
#
spring:
  datasource:
    driver-class-name: org.h2.Driver
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    databaseName:
    serverName:
    username: kemot
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: true