#                  spring:
#                    datasource:
#                      password: kemot
#                      platform: mysql
##                      url: "jdbc:mysql://35.241.170.212/adventure"
#                      url: "jdbc:mysql://google/DATABASE?cloudSqlInstance=adventure&socketFactory=com.google.cloud.sql.mysql.SocketFactory"
#                      username: kemot
#                    jpa:
#                      database: mysql
#                      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#                      hibernate:
#                        ddl-auto: none
#                        show-sql: true
##                      properties:
##                        javax:
##                          persistence:
##                            schema-generation:
##                              create-source: metadata
##                              scripts:
##                                action: create
##                                create-target: data-mysql.sql
