# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
#orb:
#  codecov: codecov/codecov@1.0.3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify services dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    general:
      artifacts:
        - "build/reports/jacoco"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests and package
      - run: gradle clean test

      - run: gradle jacocoTestReport

#      - run:
#          name: Save test results
#          command: |
#            mkdir -p ~/junit/
#            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
#          when: always
#
#      - store_test_results:
#              path: ~/junit
#
#      - store_artifacts:
#              path: ~/junit

      - run:
          name: Save test results
          command: |
            mkdir -p ~/jacoco/
            find . -type f -regex ".*/build/reports/jacoco/test/.*xml" -exec cp {} ~/jacoco/ \;
          when: always

      - store_test_results:
          path: ~/jacoco

      - store_artifacts:
          path: ~/jacoco

      - run: bash <(curl -s https://codecov.io/bash)


