apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: mongo-storage
spec:  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi